### ISSUE TITLE
Milestones for a v1.0 release

### ISSUE THREAD

**Issue by maschmann** [servergrove/ansible-symfony2#16]
Checklist of open points for a 1.0 release:

- [x] Make schema update configurable or exclude as separate module
- [x] Integrate MongoDB reindex PR
- [x] Add Travis CI testing env
- [x] Cleanup readme
- [x] Add changelog
- [x] Add datetime release-dirs as default
